@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ferreusveritas.mcf.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;