@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ferreusveritas.mcf.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;